Repository hazelcast/hazelcast-packaging, pull requests merged in 2024-08, with the labels that each got.

#212 Use internal snapshot repository for OSS snapshot packages [DI-154][DI-212][5.2.z]
  .env
  .github/workflows/assert.sh/LICENSE
  .github/workflows/assert.sh/assert.sh
  .github/workflows/build.functions.sh
  .github/workflows/build.functions_tests.sh
  .github/workflows/publish-brew-package.yml
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-packages.yml
  .github/workflows/publish-rpm-package.yml
  build-hazelcast-deb-package.sh
  build-hazelcast-homebrew-package.sh
  build-hazelcast-rpm-package.sh
  common.sh
  common_tests.sh
  packages/brew/test_brew_functions.sh
  test.sh
  test_scripts.sh
Labels: Source: Internal, Type: Enhancement

#215 Make `test-local` repos private [DI-222] [5.2.z]
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
Labels: Source: Internal

#217 Make `test-local` repos private [DI-222] [5.4.z]
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
Labels: Source: Internal

#218 Make `test-local` repos private [DI-222] [5.3.z]
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
Labels: Source: Internal

#221 Fix private test repository access [DI-236]
  .github/workflows/publish-brew-package.yml
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
  common.sh
Labels: bug, Source: Internal

#224 Remove all DEVEL references [DI-241]
  README.md
  build-hazelcast-homebrew-package.sh
  common.sh
  common_tests.sh
  packages/brew/brew_functions_tests.sh
  pom.xml
  repos/prod/hazelcast-rpm-devel.repo
  repos/test/hazelcast-rpm-devel.repo
Labels: Source: Internal

#227 Fix private test repository access (#221) [DI-236][5.5.z]
  .github/workflows/publish-brew-package.yml
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
  common.sh
Labels: Source: Internal

#228 Fix private test repository access (#221) [DI-236][5.3.z]
  .github/workflows/publish-brew-package.yml
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
  common.sh
Labels: Source: Internal

#229 Fix private test repository access (#221) [DI-236][5.4.z]
  .github/workflows/publish-brew-package.yml
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
  build-hazelcast-deb-package.sh
  build-hazelcast-homebrew-package.sh
  build-hazelcast-rpm-package.sh
  common.sh
Labels: Source: Internal

#230 Fix private test repository access (#221) [DI-236][5.2.z]
  .github/workflows/publish-brew-package.yml
  .github/workflows/publish-deb-package.yml
  .github/workflows/publish-rpm-package.yml
  common.sh
Labels: Source: Internal

#231 Remove all DEVEL references [DI-241][5.5.z]
  README.md
  build-hazelcast-homebrew-package.sh
  common.sh
  common_tests.sh
  packages/brew/test_brew_functions.sh
  pom.xml
  repos/prod/hazelcast-rpm-devel.repo
  repos/test/hazelcast-rpm-devel.repo
Labels: Source: Internal

#232 Remove all DEVEL references [DI-241][5.4.z]
  README.md
  build-hazelcast-homebrew-package.sh
  common.sh
  common_tests.sh
  packages/brew/test_brew_functions.sh
  pom.xml
  repos/prod/hazelcast-rpm-devel.repo
  repos/test/hazelcast-rpm-devel.repo
Labels: Source: Internal

#233 Remove all DEVEL references [DI-241][5.3.z]
  README.md
  build-hazelcast-homebrew-package.sh
  common.sh
  common_tests.sh
  packages/brew/test_brew_functions.sh
  pom.xml
  repos/prod/hazelcast-rpm-devel.repo
  repos/test/hazelcast-rpm-devel.repo
Labels: Source: Internal

#234 Remove all DEVEL references [DI-241][5.2.z]
  README.md
  build-hazelcast-homebrew-package.sh
  common.sh
  common_tests.sh
  packages/brew/test_brew_functions.sh
  pom.xml
  repos/prod/hazelcast-rpm-devel.repo
  repos/test/hazelcast-rpm-devel.repo
Labels: Source: Internal
